version: "3.7"
services:
  yunding:
    pid: yunding
    container_name: yunding-8.1
    image: yunding-8.1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ../:/var/www/html
      - ./logs:/var/log/php/
    env_file:
      - .env
    restart: always